version: "3.9"

networks:
  bridge:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      bridge:
        aliases:
          - zookeeper

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # JMX_PORT: 9998
    networks:
      bridge:
        aliases:
          - kafka

  producer:
    build: ./producer
    image: producer
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      PRODUCER_INTERVAL: 100
    networks:
      bridge:
        aliases:
          - produser

  # flink-processor:
  #   image: flink
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_SERVER: "kafka:9092"
  #     ZOOKEEPER_SERVER: "zookeeper:32181"
  #     PRODUCER_INTERVAL: 100
  #     DISABLE_JEMALLOC: "true"
  #   networks:
  #     - bridge

  flink-jobmanager:
    build: ./flink_processor
    image: flink
    command: jobmanager
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      PRODUCER_INTERVAL: 100
      DISABLE_JEMALLOC: "true"
    ports:
      - "8081:8081" # Flink Web UI
    networks:
      - bridge

  flink-taskmanager:
    build: ./flink_processor
    image: flink
    command: taskmanager
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      PRODUCER_INTERVAL: 100
      DISABLE_JEMALLOC: "true"
    depends_on:
      - flink-jobmanager
    networks:
      - bridge
  # postgres:
  #   build:
  #     context: ./postgres
  #   container_name: postgres
  #   restart: always
  #   environment:
  #       - POSTGRES_USER=postgres
  #       - POSTGRES_PASSWORD=postgres
  #       - POSTGRES_DB=postgres
  #   logging:
  #       options:
  #           max-size: 10m
  #           max-file: "3"
  #   ports:
  #   - 5438:5432
  #   networks:
  #     - bridge

volumes:
  settings:
  data:
